; BME280 — Adafruit library
; ESP32-C3 DevKitC-02

[env:esp32-c3-devkitc-02]
platform = espressif32
board = esp32-c3-devkitc-02
framework = arduino
lib_extra_dirs =
	../../libraries
lib_deps =
	adafruit/Adafruit BME280 Library
	adafruit/Adafruit Unified Sensor
	adafruit/Adafruit BusIO
build_flags =
	-I../../common
	-std=gnu++17
	-DBOARD_HAS_PSRAM=0
build_unflags =
	-std=gnu++11
monitor_speed = 115200
upload_port = /dev/cu.usb*
monitor_port = /dev/cu.usb*
