[platformio]
extra_configs = ../../platformio-common.ini

[env:adafruit_feather_esp32s3]
extends = esp32s3_base
lib_extra_dirs =
    ../../libraries
lib_deps = arduino-libraries/Ethernet@^2.0.2
build_flags =
    ${esp32s3_base.build_flags}
    -I../../common
    -I../../Hotfire_Code/common
    -I../../Avionics_State_Machine_Drafts
    -DBOARD_HAS_PSRAM=0
