[platformio]
extra_configs = ../../platformio-common.ini

[env:esp32s3_wroom_no_psram]
extends = esp32s3_base
upload_port = COM7
monitor_port = COM7
lib_extra_dirs =
    ~/Documents/Arduino/libraries
    ../libraries
lib_deps =
    arduino-libraries/Ethernet
