[platformio]
extra_configs = ../platformio-common.ini

[env:adafruit_feather_esp32s3]
extends = esp32s3_opi_base
lib_extra_dirs =
    ../libraries
lib_deps = arduino-libraries/Ethernet@^2.0.2
build_flags =
    ${esp32s3_opi_base.build_flags}
    -I../../common
