; DAN-E Avionics - ESP32-C6 flight computer

[platformio]
extra_configs = ../platformio-common.ini

[env:esp32-c6-devkitc-1]
extends = esp32c6_usb_base
lib_extra_dirs =
    ../libraries
lib_deps =
    sparkfun/SparkFun LPS28DFW Arduino Library
    marzogh/SPIMemory
    adafruit/Adafruit Unified Sensor
    adafruit/Adafruit BusIO
build_flags =
    ${esp32c6_usb_base.build_flags}
    -I../common
