[platformio]
extra_configs = ../../platformio-common.ini

[env:esp32-c6-devkitc-1]
extends = esp32c6_base
lib_extra_dirs =
    ../../libraries
build_flags =
    ${esp32c6_base.build_flags}
    -I../../common
