; LC1 is N16R2 and LC2 is N4R8 (mistake but resoldering is annoying).
; For magic-ass reasons forcing 4MB flash + default partitions makes
; the same image upload to both correctly. See esp32s3_lc_base.

[platformio]
extra_configs = ../../platformio-common.ini

[env:adafruit_feather_esp32s3]
extends = esp32s3_lc_base
lib_extra_dirs =
    ../../libraries
lib_deps =
    arduino-libraries/Ethernet@^2.0.2
    Update
build_flags =
    ${esp32s3_lc_base.build_flags}
    -I../common
    -I../../common
    -DBOARD_HAS_PSRAM=0
