; LPS28DFW barometer - SparkFun library. ESP32-C6 DevKitC-1.
; https://registry.platformio.org/libraries/sparkfun/SparkFun%20LPS28DFW%20Arduino%20Library

[platformio]
extra_configs = ../../platformio-common.ini

[env:esp32-c6-devkitc-1]
extends = esp32c6_base
lib_extra_dirs =
    ../../libraries
lib_deps =
    sparkfun/SparkFun LPS28DFW Arduino Library
build_flags =
    ${esp32c6_base.build_flags}
    -I../../common
