/**
 * The shipped stand drawing (feed-twin/backend/diagrams/copv_study_gn2.json), trimmed to what the hero
 * reads: topology, positions, labels, fluids, clips and tank volumes. A test fixture.
 */
export const STAND_DOC = {
  nodes: [
    {"id": "KB1", "position": {"x": 40, "y": 300}, "data": {"componentType": "KBOTTLE", "label": "KB-GN2", "fluid": "nitrogen", "params": {"volume": {"value": 4.6871, "unit": "L"}}}},
    {"id": "PT_HI", "position": {"x": 40, "y": 235}, "data": {"componentType": "PT", "label": "PT-GN2-HI", "attachedTo": "KB1"}},
    {"id": "PR_C", "position": {"x": 150, "y": 415}, "data": {"componentType": "PR", "label": "PR-CTRL", "fluid": "nitrogen", "options": {"domeLoaded": "no"}, "params": {"setpoint": {"value": 450, "unit": "psi"}}}},
    {"id": "PR_D", "position": {"x": 250, "y": 300}, "data": {"componentType": "PR", "label": "PR-DOME", "fluid": "nitrogen", "options": {"domeLoaded": "yes"}, "params": {"setpoint": {"value": 500, "unit": "psi"}}}},
    {"id": "PT_REG", "position": {"x": 360, "y": 235}, "data": {"componentType": "PT", "label": "PT-GN2-REG", "attachedTo": "MF2"}},
    {"id": "MF1", "position": {"x": 150, "y": 300}, "data": {"componentType": "MANIFOLD", "label": "MAN-GN2", "fluid": "nitrogen"}},
    {"id": "SV_GN2_VENT", "position": {"x": 360, "y": 175}, "data": {"componentType": "SOL", "label": "SV-GN2-VENT", "fluid": "nitrogen"}},
    {"id": "VENT_GN2", "position": {"x": 360, "y": 115}, "data": {"componentType": "VENT", "label": "VENT-GN2"}},
    {"id": "SV_LOX_PRESS", "position": {"x": 460, "y": 210}, "data": {"componentType": "SOL", "label": "SV-LOX-PRESS", "fluid": "nitrogen"}},
    {"id": "OXT", "position": {"x": 570, "y": 210}, "data": {"componentType": "TANK", "label": "TK-LOX", "fluid": "oxygen", "params": {"volume": {"value": 15.1, "unit": "L"}}}},
    {"id": "PT_OXU", "position": {"x": 570, "y": 140}, "data": {"componentType": "PT", "label": "PT-OX-UP", "attachedTo": "OXT"}},
    {"id": "SV_LOX_VENT", "position": {"x": 680, "y": 140}, "data": {"componentType": "SOL", "label": "SV-LOX-VENT", "fluid": "nitrogen"}},
    {"id": "VENT_LOX", "position": {"x": 780, "y": 140}, "data": {"componentType": "VENT", "label": "VENT-LOX"}},
    {"id": "SV_LOX_FILL", "position": {"x": 460, "y": 140}, "data": {"componentType": "SOL", "label": "SV-LOX-FILL", "fluid": "oxygen"}},
    {"id": "MVO", "position": {"x": 700, "y": 250}, "data": {"componentType": "SOL", "label": "MV-OX", "fluid": "oxygen"}},
    {"id": "PT_OXD", "position": {"x": 860, "y": 200}, "data": {"componentType": "PT", "label": "PT-OX-DN", "attachedTo": "MVO", "options": {"side": "downstream"}}},
    {"id": "SV_FUEL_PRESS", "position": {"x": 460, "y": 400}, "data": {"componentType": "SOL", "label": "SV-FUEL-PRESS", "fluid": "nitrogen"}},
    {"id": "FUT", "position": {"x": 570, "y": 400}, "data": {"componentType": "TANK", "label": "TK-FUEL", "fluid": "ethanol", "params": {"volume": {"value": 8.67, "unit": "L"}}}},
    {"id": "PT_FUU", "position": {"x": 570, "y": 470}, "data": {"componentType": "PT", "label": "PT-FU-UP", "attachedTo": "FUT"}},
    {"id": "SV_FUEL_VENT", "position": {"x": 680, "y": 470}, "data": {"componentType": "SOL", "label": "SV-FUEL-VENT", "fluid": "nitrogen"}},
    {"id": "VENT_FUEL", "position": {"x": 780, "y": 470}, "data": {"componentType": "VENT", "label": "VENT-FUEL"}},
    {"id": "MVF", "position": {"x": 700, "y": 350}, "data": {"componentType": "SOL", "label": "MV-FU", "fluid": "ethanol"}},
    {"id": "PT_FUD", "position": {"x": 860, "y": 400}, "data": {"componentType": "PT", "label": "PT-FU-DN", "attachedTo": "MVF", "options": {"side": "downstream"}}},
    {"id": "ENG", "position": {"x": 950, "y": 300}, "data": {"componentType": "ENGINE", "label": "ENG-01"}},
    {"id": "MF2", "position": {"x": 360, "y": 300}, "data": {"componentType": "MANIFOLD", "label": "MAN-REG", "fluid": "nitrogen"}},
    {"id": "TC_REGI", "position": {"x": 760, "y": 150}, "data": {"componentType": "TC", "label": "TC-REG-IN", "attachedTo": "MF1"}},
    {"id": "TC_REGO", "position": {"x": 760, "y": 250}, "data": {"componentType": "TC", "label": "TC-REG-OUT", "attachedTo": "MF2"}},
    {"id": "RTD_OXT", "position": {"x": 40, "y": 470}, "data": {"componentType": "RTD", "label": "RTD-LOX", "attachedTo": "OXT"}},
    {"id": "TC_OXD", "position": {"x": 40, "y": 700}, "data": {"componentType": "TC", "label": "TC-OX-DN", "attachedTo": "MVO", "options": {"side": "downstream"}}},
    {"id": "TC_FUD", "position": {"x": 600, "y": 700}, "data": {"componentType": "TC", "label": "TC-FU-DN", "attachedTo": "MVF", "options": {"side": "downstream"}}},
  ],
  edges: [
    {"id": "l_kb", "source": "KB1", "target": "MF1"},
    {"id": "l_ctrl", "source": "MF1", "target": "PR_C"},
    {"id": "l_dome", "source": "PR_C", "target": "PR_D"},
    {"id": "l_reg", "source": "MF1", "target": "PR_D"},
    {"id": "l_gn2vent2", "source": "SV_GN2_VENT", "target": "VENT_GN2"},
    {"id": "l_oxpress", "source": "SV_LOX_PRESS", "target": "OXT"},
    {"id": "l_oxfill", "source": "SV_LOX_FILL", "target": "OXT"},
    {"id": "l_oxvent", "source": "OXT", "target": "SV_LOX_VENT"},
    {"id": "l_oxvent2", "source": "SV_LOX_VENT", "target": "VENT_LOX"},
    {"id": "l_ox1", "source": "OXT", "target": "MVO"},
    {"id": "l_ox2", "source": "MVO", "target": "ENG"},
    {"id": "l_fupress", "source": "SV_FUEL_PRESS", "target": "FUT"},
    {"id": "l_fuvent", "source": "FUT", "target": "SV_FUEL_VENT"},
    {"id": "l_fuvent2", "source": "SV_FUEL_VENT", "target": "VENT_FUEL"},
    {"id": "l_fu1", "source": "FUT", "target": "MVF"},
    {"id": "l_fu2", "source": "MVF", "target": "ENG"},
    {"id": "l_reg_out", "source": "PR_D", "target": "MF2"},
    {"id": "l_gn2vent", "source": "MF2", "target": "SV_GN2_VENT"},
    {"id": "l_oxpress_in", "source": "MF2", "target": "SV_LOX_PRESS"},
    {"id": "l_fupress_in", "source": "MF2", "target": "SV_FUEL_PRESS"},
  ],
};
