[platformio]
extra_configs = ../../platformio-common.ini

[env:esp32dev]
extends = esp32_classic_base
lib_extra_dirs =
    ~/Documents/Arduino/libraries
    ../libraries
lib_deps =
    arduino-libraries/Ethernet
    madhephaestus/ESP32Encoder @ 0.11.8
