; Stacklight Driver - ESP32-C6 + W5500, DAQv2-Comms

[platformio]
extra_configs = ../platformio-common.ini

[env:esp32_c6]
extends = esp32c6_usb_base
lib_extra_dirs =
    ../libraries
lib_deps =
    arduino-libraries/Ethernet@^2.0.2
    Update
build_flags =
    ${esp32c6_usb_base.build_flags}
    -I../libraries
    -I../Hotfire_Code/common
upload_port = /dev/cu.usb*
monitor_port = /dev/cu.usb*
