[platformio]
extra_configs = ../platformio-common.ini

[env:esp32c3]
extends = esp32c3_usb_base
lib_extra_dirs =
    ../libraries
lib_deps =
    adafruit/Adafruit BME280 Library
    adafruit/Adafruit Unified Sensor
    adafruit/Adafruit BusIO
    arduino-libraries/Ethernet
    Update
build_flags =
    ${esp32c3_usb_base.build_flags}
    -I../common
    -I../Hotfire_Code/common
